DROP PROCEDURE IF EXISTS wscpa_dw.sp_load_dim_firms;

DELIMITER $$

CREATE PROCEDURE wscpa_dw.sp_load_dim_firms()
BEGIN

    INSERT INTO wscpa_dw.dim_Firms
    (
        FirmsKey,
        FirmsCustomInformationKey,
        MainOfficesKey,
        ExhibitorPrimaryContactsKey,
        ExhibitorEmergencyContactsKey,
        PersonsInChargeKey,
        FirmCode,
        FirmName,
        FirmAddress,
        FirmCity,
        FirmState,
        FirmZIP,
        FirmZIPLatitude,
        FirmZIPLongitude,
        FirmZIPGeoLocation,
        FirmChapter,
        FirmCounty,
        FirmCountry,
        AICPANumber,
        ReviewBillingClass,
        GroupMembershipYN,
        GeneralBusinessType,
        SpecificBusinessType,
        EntityType,
        FirstFirmContributionDate,
        CompanyHeldPubliclyYN,
        PersonInCharge,
        FirmPaysDuesYN,
        RevenueRange,
        ClientReferralStatus,
        ClientReferralChapterList,
        ClientReferralServiceList,
        ClientReferralCityList,
        ClientReferralIndustryList,
        MediaCirculation,
        MediaFormat,
        MediaFrequency,
        MediaGeneralType,
        MediaSpecificType,
        ReviewStatus,
        ReviewDivision,
        ReviewLocation,
        ReviewType,
        ReviewSource,
        LastReviewDate,
        NextReviewDate,
        ExhibitorYearExhibiting,
        ExhibitorStatus,
        ExhibitorProductTypesList,
        ExhibitorTypesList,
        ExhibitorOtherList,
        FirmsRowEffectiveDate,
        FirmsRowExpirationDate,
        FirmsRowChangeReason,
        FirmsRowStatus
    )
    SELECT
        CAST(firms_key AS SIGNED),
        CAST(firms_custom_information_key AS SIGNED),
        CAST(main_offices_key AS SIGNED),
        CAST(exhibitor_primary_contacts_key AS SIGNED),
        CAST(exhibitor_emergency_contacts_key AS SIGNED),
        CAST(persons_in_charge_key AS SIGNED),
        CAST(firm_code AS CHAR(5)),
        CAST(firm_name AS CHAR(75)),
        CAST(firm_address AS CHAR(37)),
        CAST(firm_city AS CHAR(37)),
        CAST(firm_state AS CHAR(2)),
        CAST(firm_zip AS CHAR(5)),
        CAST(firm_zip_latitude AS DOUBLE),
        CAST(firm_zip_longitude AS DOUBLE),
        POINT(
            CAST(firm_zip_longitude AS DOUBLE),
            CAST(firm_zip_latitude AS DOUBLE)
        ),
        CAST(firm_chapter AS CHAR(50)),
        CAST(firm_county AS CHAR(50)),
        CAST(firm_country AS CHAR(37)),
        CAST(aicpa_number AS CHAR(12)),
        CAST(review_billing_class AS CHAR(3)),
        CAST(group_membership_yn AS CHAR(3)),
        CAST(general_business_type AS CHAR(50)),
        CAST(specific_business_type AS CHAR(50)),
        CAST(entity_type AS CHAR(50)),
        CAST(first_firm_contribution_date AS DATE),
        CAST(company_held_publicly_yn AS CHAR(3)),
        CAST(person_in_charge AS CHAR(37)),
        CAST(firm_pays_dues_yn AS CHAR(3)),
        CAST(revenue_range AS CHAR(50)),
        CAST(client_referral_status AS CHAR(10)),
        CAST(client_referral_chapter_list AS CHAR),
        CAST(client_referral_service_list AS CHAR),
        CAST(client_referral_city_list AS CHAR),
        CAST(client_referral_industry_list AS CHAR),
        CAST(media_circulation AS SIGNED),
        CAST(media_format AS CHAR(50)),
        CAST(media_frequency AS CHAR(50)),
        CAST(media_general_type AS CHAR(50)),
        CAST(media_specific_type AS CHAR(50)),
        CAST(review_status AS CHAR(50)),
        CAST(review_division AS CHAR(50)),
        CAST(review_location AS CHAR(50)),
        CAST(review_type AS CHAR(50)),
        CAST(review_source AS CHAR(50)),
        CAST(last_review_date AS DATE),
        CAST(next_review_date AS DATE),
        CAST(exhibitor_year_exhibiting AS CHAR(4)),
        CAST(exhibitor_status AS CHAR(50)),
        CAST(exhibitor_product_types_list AS CHAR),
        CAST(exhibitor_types_list AS CHAR),
        CAST(exhibitor_other_list AS CHAR),
        CAST(firms_row_effective_date AS DATETIME),
        CAST(firms_row_expiration_date AS DATETIME),
        CAST(firms_row_change_reason AS CHAR),
        CAST(firms_row_status AS CHAR(10))
    FROM wscpa_amnet.staging_firms

    ON DUPLICATE KEY UPDATE
        FirmsCustomInformationKey = VALUES(FirmsCustomInformationKey),
        MainOfficesKey = VALUES(MainOfficesKey),
        ExhibitorPrimaryContactsKey = VALUES(ExhibitorPrimaryContactsKey),
        ExhibitorEmergencyContactsKey = VALUES(ExhibitorEmergencyContactsKey),
        PersonsInChargeKey = VALUES(PersonsInChargeKey),
        FirmCode = VALUES(FirmCode),
        FirmName = VALUES(FirmName),
        FirmAddress = VALUES(FirmAddress),
        FirmCity = VALUES(FirmCity),
        FirmState = VALUES(FirmState),
        FirmZIP = VALUES(FirmZIP),
        FirmZIPLatitude = VALUES(FirmZIPLatitude),
        FirmZIPLongitude = VALUES(FirmZIPLongitude),
        FirmZIPGeoLocation = VALUES(FirmZIPGeoLocation),
        FirmChapter = VALUES(FirmChapter),
        FirmCounty = VALUES(FirmCounty),
        FirmCountry = VALUES(FirmCountry),
        AICPANumber = VALUES(AICPANumber),
        ReviewBillingClass = VALUES(ReviewBillingClass),
        GroupMembershipYN = VALUES(GroupMembershipYN),
        GeneralBusinessType = VALUES(GeneralBusinessType),
        SpecificBusinessType = VALUES(SpecificBusinessType),
        EntityType = VALUES(EntityType),
        FirstFirmContributionDate = VALUES(FirstFirmContributionDate),
        CompanyHeldPubliclyYN = VALUES(CompanyHeldPubliclyYN),
        PersonInCharge = VALUES(PersonInCharge),
        FirmPaysDuesYN = VALUES(FirmPaysDuesYN),
        RevenueRange = VALUES(RevenueRange),
        ClientReferralStatus = VALUES(ClientReferralStatus),
        ClientReferralChapterList = VALUES(ClientReferralChapterList),
        ClientReferralServiceList = VALUES(ClientReferralServiceList),
        ClientReferralCityList = VALUES(ClientReferralCityList),
        ClientReferralIndustryList = VALUES(ClientReferralIndustryList),
        MediaCirculation = VALUES(MediaCirculation),
        MediaFormat = VALUES(MediaFormat),
        MediaFrequency = VALUES(MediaFrequency),
        MediaGeneralType = VALUES(MediaGeneralType),
        MediaSpecificType = VALUES(MediaSpecificType),
        ReviewStatus = VALUES(ReviewStatus),
        ReviewDivision = VALUES(ReviewDivision),
        ReviewLocation = VALUES(ReviewLocation),
        ReviewType = VALUES(ReviewType),
        ReviewSource = VALUES(ReviewSource),
        LastReviewDate = VALUES(LastReviewDate),
        NextReviewDate = VALUES(NextReviewDate),
        ExhibitorYearExhibiting = VALUES(ExhibitorYearExhibiting),
        ExhibitorStatus = VALUES(ExhibitorStatus),
        ExhibitorProductTypesList = VALUES(ExhibitorProductTypesList),
        ExhibitorTypesList = VALUES(ExhibitorTypesList),
        ExhibitorOtherList = VALUES(ExhibitorOtherList),
        FirmsRowEffectiveDate = VALUES(FirmsRowEffectiveDate),
        FirmsRowExpirationDate = VALUES(FirmsRowExpirationDate),
        FirmsRowChangeReason = VALUES(FirmsRowChangeReason),
        FirmsRowStatus = VALUES(FirmsRowStatus);

END$$

DELIMITER ;
