DROP PROCEDURE IF EXISTS wscpa_dw.sp_load_fact_calendar_month_individual_snapshots;

DELIMITER $$

CREATE PROCEDURE wscpa_dw.sp_load_fact_calendar_month_individual_snapshots()
BEGIN

    INSERT INTO wscpa_dw.fact_CalendarMonthIndividualSnapshots
    (
        MonthsKey,
        IndividualsKey,
        EmployersKey,
        PriorMonthIndividualsKey,
        PriorDuesYearIndividualsKey,
        MemberStatusChangeReasonsKey,
        IndividualID,
        CMAge,
        CMAgeBracket,
        CMMemberChangeCount,
        CMMemberStatusChangeCount,
        CMBillingClassChangeCount,
        CMMonthsCertified,
        CMCreditHoursEarned,
        CMDuesGrossBillingTotal,
        CMDuesAdjustmentsTotal,
        CMDuesNetBillingTotal,
        CMDuesGrossPaymentsTotal,
        CMDuesRefundsTotal,
        CMDuesNetPaymentsTotal,
        CMContributionTotal,
        CMContributionCount,
        CMCommitteeMembershipCount,
        CMCommitteeAttendanceCount,
        CMEventFeeTotal,
        CMEventPaymentTotal,
        CMEventRegistrationCount,
        CMEventAttendanceCount,
        CMProductSalesQuantity,
        CMProductExtendedNetPriceTotal,
        CMProductExtendedItemCostTotal,
        CMProductMargin,
        CMVolunteerAssignmentCount
    )
    SELECT
        CAST(months_key AS SIGNED),
        CAST(individuals_key AS SIGNED),
        CAST(employers_key AS SIGNED),
        CAST(prior_month_data_key AS SIGNED),
        CAST(prior_dues_year_data_key AS SIGNED),
        CAST(member_status_change_reasons_key AS SIGNED),
        CAST(individual_id AS CHAR(20)),
        CAST(cm_age AS SIGNED),
        CAST(cm_age_bracket AS CHAR(10)),
        CAST(cm_member_change_count AS SIGNED),
        CAST(cm_member_status_change_count AS SIGNED),
        CAST(cm_billing_class_change_count AS SIGNED),
        CAST(cm_months_certified AS SIGNED),
        CAST(cm_credit_hours_earned AS DECIMAL(6,2)),
        CAST(cm_dues_gross_billing AS DECIMAL(12,2)),
        CAST(cm_dues_adjustments AS DECIMAL(12,2)),
        CAST(cm_dues_net_billing AS DECIMAL(12,2)),
        CAST(cm_dues_gross_payments AS DECIMAL(12,2)),
        CAST(cm_dues_refunds AS DECIMAL(12,2)),
        CAST(cm_dues_net_payments AS DECIMAL(12,2)),
        CAST(cm_contribution_total AS DECIMAL(12,2)),
        CAST(cm_contribution_count AS SIGNED),
        CAST(cm_committee_membership_count AS SIGNED),
        CAST(cm_committee_attendance_count AS SIGNED),
        CAST(cm_event_fee_total AS DECIMAL(12,2)),
        CAST(cm_event_payment_total AS DECIMAL(12,2)),
        CAST(cm_event_registration_count AS SIGNED),
        CAST(cm_event_attendance_count AS SIGNED),
        CAST(cm_product_sales_quantity AS SIGNED),
        CAST(cm_product_extended_net_price_total AS DECIMAL(12,2)),
        CAST(cm_product_extended_item_cost_total AS DECIMAL(12,2)),
        CAST(cm_product_margin AS DECIMAL(12,2)),
        CAST(cm_volunteer_assignment_count AS SIGNED)
    FROM wscpa_amnet.staging_calendar_month_individual_snapshots

    ON DUPLICATE KEY UPDATE
        EmployersKey = VALUES(EmployersKey),
        PriorMonthIndividualsKey = VALUES(PriorMonthIndividualsKey),
        PriorDuesYearIndividualsKey = VALUES(PriorDuesYearIndividualsKey),
        MemberStatusChangeReasonsKey = VALUES(MemberStatusChangeReasonsKey),
        IndividualID = VALUES(IndividualID),
        CMAge = VALUES(CMAge),
        CMAgeBracket = VALUES(CMAgeBracket),
        CMMemberChangeCount = VALUES(CMMemberChangeCount),
        CMMemberStatusChangeCount = VALUES(CMMemberStatusChangeCount),
        CMBillingClassChangeCount = VALUES(CMBillingClassChangeCount),
        CMMonthsCertified = VALUES(CMMonthsCertified),
        CMCreditHoursEarned = VALUES(CMCreditHoursEarned),
        CMDuesGrossBillingTotal = VALUES(CMDuesGrossBillingTotal),
        CMDuesAdjustmentsTotal = VALUES(CMDuesAdjustmentsTotal),
        CMDuesNetBillingTotal = VALUES(CMDuesNetBillingTotal),
        CMDuesGrossPaymentsTotal = VALUES(CMDuesGrossPaymentsTotal),
        CMDuesRefundsTotal = VALUES(CMDuesRefundsTotal),
        CMDuesNetPaymentsTotal = VALUES(CMDuesNetPaymentsTotal),
        CMContributionTotal = VALUES(CMContributionTotal),
        CMContributionCount = VALUES(CMContributionCount),
        CMCommitteeMembershipCount = VALUES(CMCommitteeMembershipCount),
        CMCommitteeAttendanceCount = VALUES(CMCommitteeAttendanceCount),
        CMEventFeeTotal = VALUES(CMEventFeeTotal),
        CMEventPaymentTotal = VALUES(CMEventPaymentTotal),
        CMEventRegistrationCount = VALUES(CMEventRegistrationCount),
        CMEventAttendanceCount = VALUES(CMEventAttendanceCount),
        CMProductSalesQuantity = VALUES(CMProductSalesQuantity),
        CMProductExtendedNetPriceTotal = VALUES(CMProductExtendedNetPriceTotal),
        CMProductExtendedItemCostTotal = VALUES(CMProductExtendedItemCostTotal),
        CMProductMargin = VALUES(CMProductMargin),
        CMVolunteerAssignmentCount = VALUES(CMVolunteerAssignmentCount);

END$$

DELIMITER ;
