DROP PROCEDURE IF EXISTS wscpa_dw.sp_load_dim_dates;

DELIMITER $$

CREATE PROCEDURE wscpa_dw.sp_load_dim_dates()
BEGIN

    DELETE FROM wscpa_dw.dim_Dates;

    INSERT INTO wscpa_dw.dim_Dates
    (
        DatesKey,
        Date,
        FullDate,
        CalendarYear,
        CalendarYearAndQuarter,
        CalendarQuarter,
        CalendarYearAndMonth,
        CalendarMonthNumber,
        CalendarMonthName,
        CalendarMonthAbbreviation,
        WeekOfCalendarYear,
        ISOWeekOfYear,
        WeekOfMonth,
        DayOfCalendarYear,
        DayOfMonth,
        DayOfMonthOrdinal,
        DayOfWeek,
        DayOfWeekName,
        DayType,
        HolidayName,
        DuesYearBeginDate,
        DuesYearEndDate,
        DuesYearName,
        DuesYearAndQuarter,
        DuesQuarter,
        DuesYearAndPeriod,
        DuesPeriod,
        WeekOfDuesYear,
        DayOfDuesYear,
        EventYearBeginDate,
        EventYearEndDate,
        EventYearName,
        EventYearAndQuarter,
        EventQuarter,
        EventYearAndPeriod,
        EventPeriod,
        WeekOfEventYear,
        DayOfEventYear,
        AccountingYearBeginDate,
        AccountingYearEndDate,
        AccountingYearName,
        AccountingYearAndQuarter,
        AccountingQuarter,
        AccountingYearAndPeriod,
        AccountingPeriod,
        WeekOfAccountingYear,
        DayOfAccountingYear,
        PeriodCounter
    )
    SELECT
        CAST(dates_key AS SIGNED),
        CAST(date AS DATE),
        CAST(full_date AS CHAR(10)),
        CAST(calendar_year AS SIGNED),
        CAST(calendar_year_and_quarter AS CHAR(8)),
        CAST(calendar_quarter AS SIGNED),
        CAST(calendar_year_and_month AS CHAR(8)),
        CAST(calendar_month_number AS SIGNED),
        CAST(calendar_month_name AS CHAR(10)),
        CAST(calendar_month_abbreviation AS CHAR(3)),
        CAST(week_of_the_calendar_year AS SIGNED),
        CAST(iso_week_of_the_year AS SIGNED),
        CAST(week_of_the_month AS SIGNED),
        CAST(day_of_the_calendar_year AS SIGNED),
        CAST(day_of_the_month AS SIGNED),
        CAST(day_of_the_month_ordinal AS CHAR(5)),
        CAST(day_of_the_week AS SIGNED),
        CAST(day_of_the_week_name AS CHAR(9)),
        CAST(day_type AS CHAR(12)),
        CAST(holiday_name AS CHAR(24)),
        CAST(dues_year_begin_date AS DATE),
        CAST(dues_year_end_date AS DATE),
        CAST(dues_year_name AS CHAR(4)),
        CAST(dues_year_and_quarter AS CHAR(8)),
        CAST(dues_quarter AS SIGNED),
        CAST(dues_year_and_period AS CHAR(8)),
        CAST(dues_period AS SIGNED),
        CAST(week_of_the_dues_year AS SIGNED),
        CAST(day_of_the_dues_year AS SIGNED),
        CAST(event_year_begin_date AS DATE),
        CAST(event_year_end_date AS DATE),
        CAST(event_year_name AS CHAR(4)),
        CAST(event_year_and_quarter AS CHAR(8)),
        CAST(event_quarter AS SIGNED),
        CAST(event_year_and_period AS CHAR(8)),
        CAST(event_period AS SIGNED),
        CAST(week_of_the_event_year AS SIGNED),
        CAST(day_of_the_event_year AS SIGNED),
        CAST(accounting_year_begin_date AS DATE),
        CAST(accounting_year_end_date AS DATE),
        CAST(accounting_year_name AS CHAR(4)),
        CAST(accounting_year_and_quarter AS CHAR(8)),
        CAST(accounting_quarter AS SIGNED),
        CAST(accounting_year_and_period AS CHAR(8)),
        CAST(accounting_period AS SIGNED),
        CAST(week_of_the_accounting_year AS SIGNED),
        CAST(day_of_the_accounting_year AS SIGNED),
        CAST(period_counter AS SIGNED)
    FROM wscpa_amnet.staging_dates;

END$$

DELIMITER ;
