-- Create table for consolidated firm summary
CREATE TABLE IF NOT EXISTS wscpa_dw.dw_firm_summary (
  firms_key VARCHAR(100) NOT NULL,
  firm_name VARCHAR(255) DEFAULT NULL,
  firm_city VARCHAR(100) DEFAULT NULL,
  firm_state VARCHAR(50) DEFAULT NULL,
  firm_zip VARCHAR(20) DEFAULT NULL,
  general_business_type VARCHAR(100) DEFAULT NULL,
  specific_business_type VARCHAR(100) DEFAULT NULL,
  entity_type VARCHAR(100) DEFAULT NULL,
  firm_pays_dues_yn VARCHAR(10) DEFAULT NULL,
  person_in_charge VARCHAR(255) DEFAULT NULL,
  firms_row_effective_date VARCHAR(50) DEFAULT NULL,
  number_of_employees INT DEFAULT NULL,
  member_count INT DEFAULT NULL,
  member_penetration_rate DECIMAL(10,4) DEFAULT NULL,
  member_growth_decline VARCHAR(50) DEFAULT NULL,
  employee_renewal_rate DECIMAL(10,4) DEFAULT NULL,
  aggregated_dues_paid DECIMAL(19,4) DEFAULT NULL,
  current_dues_balance DECIMAL(19,4) DEFAULT NULL,
  distinct_events_attended INT DEFAULT NULL,
  employee_event_registrations INT DEFAULT NULL,
  total_cpe_hours_attended DECIMAL(10,2) DEFAULT NULL,
  total_event_fees_paid DECIMAL(19,4) DEFAULT NULL,
  last_event_date VARCHAR(50) DEFAULT NULL,
  in_house_training_purchase DECIMAL(19,4) DEFAULT NULL,
  comm_subscription_preferences TEXT DEFAULT NULL,
  comm_engagement TEXT DEFAULT NULL,
  activity_by_engagement_dimension TEXT DEFAULT NULL,
  key_contacts TEXT DEFAULT NULL,
  committee_participation_count INT DEFAULT NULL,
  employee_committee_count INT DEFAULT NULL,
  last_committee_activity_date VARCHAR(50) DEFAULT NULL,
  employee_volunteer_assignments INT DEFAULT NULL,
  employees_with_volunteer_activity INT DEFAULT NULL,
  last_volunteer_assignment_date VARCHAR(50) DEFAULT NULL,
  total_in_house_training_purchase DECIMAL(19,4) DEFAULT NULL,
  total_purchase_transactions INT DEFAULT NULL,
  total_employee_contributions DECIMAL(19,4) DEFAULT NULL,
  pac_contributions DECIMAL(19,4) DEFAULT NULL,
  foundation_contributions DECIMAL(19,4) DEFAULT NULL,
  employee_community_activity_count INT DEFAULT NULL,
  employees_with_community_activity INT DEFAULT NULL,
  last_community_activity_date VARCHAR(50) DEFAULT NULL,
  latest_firm_engagement_score DECIMAL(10,4) DEFAULT NULL,
  total_engagement_event_registrations INT DEFAULT NULL,
  total_engagement_committee_attendance INT DEFAULT NULL,
  total_engagement_contributions DECIMAL(19,4) DEFAULT NULL,
  total_engagement_volunteer_activity INT DEFAULT NULL,
  total_engagement_log_activity INT DEFAULT NULL,
  load_ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (firms_key),
  KEY idx_firm_name (firm_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
