-- Create table for loaded HubSpot contacts
CREATE TABLE IF NOT EXISTS wscpa_dw.dw_hubspot_contacts (
  hubspot_id BIGINT UNSIGNED NOT NULL,
  am_net_id VARCHAR(100) DEFAULT NULL,
  amnet_last_sync DATE DEFAULT NULL,
  company_size VARCHAR(100) DEFAULT NULL,
  cpa_exam_begin_date VARCHAR(50) DEFAULT NULL,
  cpa_exam_last_section_pass_date VARCHAR(50) DEFAULT NULL,
  cpa_exam_review_course_purchase_date VARCHAR(50) DEFAULT NULL,
  cpa_exam_section_attempt_number VARCHAR(50) DEFAULT NULL,
  cpa_exam_sections_passed VARCHAR(50) DEFAULT NULL,
  cpe_spend_current_year DECIMAL(19,2) DEFAULT NULL,
  cpe_spend_previous_fy DECIMAL(19,2) DEFAULT NULL,
  properties_created_date DATETIME DEFAULT NULL,
  date_passed_cpa_exam VARCHAR(50) DEFAULT NULL,
  email VARCHAR(255) DEFAULT NULL,
  fields_of_interest TEXT DEFAULT NULL,
  first_conversion_date VARCHAR(50) DEFAULT NULL,
  firstname VARCHAR(255) DEFAULT NULL,
  hs_analytics_num_event_completions INT DEFAULT NULL,
  hs_analytics_num_page_views INT DEFAULT NULL,
  hs_analytics_num_visits INT DEFAULT NULL,
  hs_email_click VARCHAR(50) DEFAULT NULL,
  hs_email_delivered INT DEFAULT NULL,
  hs_email_last_click_date VARCHAR(50) DEFAULT NULL,
  hs_email_last_email_name VARCHAR(255) DEFAULT NULL,
  hs_email_open INT DEFAULT NULL,
  hs_email_replied VARCHAR(50) DEFAULT NULL,
  hs_email_sends_since_last_engagement INT DEFAULT NULL,
  hs_email_type VARCHAR(100) DEFAULT NULL,
  hs_email_confirmation_status VARCHAR(100) DEFAULT NULL,
  hs_last_sales_activity_timestamp DATETIME DEFAULT NULL,
  hs_lead_status VARCHAR(100) DEFAULT NULL,
  hs_object_id BIGINT UNSIGNED DEFAULT NULL,
  hs_sales_email_last_clicked VARCHAR(50) DEFAULT NULL,
  hs_sales_email_last_opened VARCHAR(50) DEFAULT NULL,
  hs_sales_email_last_replied VARCHAR(50) DEFAULT NULL,
  hubspot_score INT DEFAULT NULL,
  properties_last_modified_date DATETIME DEFAULT NULL,
  lastname VARCHAR(255) DEFAULT NULL,
  notes_last_contacted VARCHAR(100) DEFAULT NULL,
  notes_last_updated VARCHAR(100) DEFAULT NULL,
  created_at DATETIME DEFAULT NULL,
  updated_at DATETIME DEFAULT NULL,
  archived TINYINT(1) DEFAULT NULL,
  hubspot_url VARCHAR(1024) DEFAULT NULL,
  source_file VARCHAR(512) DEFAULT NULL,
  load_ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (hubspot_id),
  KEY idx_hs_object_id (hs_object_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
