DROP PROCEDURE IF EXISTS wscpa_dw.sp_load_dim_individuals;

DELIMITER $$

CREATE PROCEDURE wscpa_dw.sp_load_dim_individuals()
BEGIN

    INSERT INTO wscpa_dw.dim_Individuals
    (
        IndividualsKey,
        IndividualsCustomInformationKey,
        EmployersKey,
        IndividualID,
        FullName,
        FullNameWithCredentials,
        Gender,
        Ethnicity,
        DateOfBirth,
        Age,
        AgeBracket,
        Generation,
        Spouse,
        HomeAddress,
        HomeCity,
        HomeState,
        HomeZIP,
        HomeZIPLatitude,
        HomeZIPLongitude,
        HomeZIPGeoLocation,
        HomeCountry,
        HomePhone,
        PreferredAddress,
        PreferredCity,
        PreferredState,
        PreferredZIP,
        PreferredZIPLatitude,
        PreferredZIPLongitude,
        PreferredZIPGeoLocation,
        PreferredCountry,
        EmployerAdministratorYN,
        HouseDistrict,
        SenateDistrict,
        CongressionalDistrict,
        MailingLists,
        AreasOfExpertiseList,
        FieldsOfInterestList,
        SpecialNeedsList,
        GroupMembershipsList,
        ProspectiveMemberSourcesList,
        SectionsList,
        JoinedDate,
        SecondaryJoinedDate,
        ConsecutiveYearsOfMembership,
        CumulativeYearsOfMembership,
        FirstIndividualContributionDate,
        LastCPEDate,
        InStateCertificationDate,
        OutOfStateCertificationDate,
        OriginalCertificationDate,
        ReinstatementDate,
        TerminationDate,
        Credentials,
        PositionCode,
        PositionDescription,
        MemberYN,
        CPAYN,
        MemberStatus,
        MemberType,
        DuesBillingClass,
        ActualChapter,
        PreferredChapter,
        EmailAddress,
        Solicitation,
        CertificationStatus,
        LicenseStatus,
        PeerReviewStatus,
        AICPAMemberYN,
        LeaderStatus,
        GovernmentOffice,
        GovernmentPosition,
        GovernmentStatus,
        GovernmentDistrict,
        GovernmentLastYearInOffice,
        GovernmentPoliticalParty,
        VolunteerPublicSpeakingRating,
        VolunteerRadioRating,
        VolunteerSpecialProjectsRating,
        VolunteerTelevisionRating,
        VolunteerWritingRating,
        VolunteerCommittedYN,
        VolunteerVerifiedYN,
        VolunteerLastAssignmentDate,
        VolunteerStatus,
        NamesControl,
        InitialNonMemberType,
        InitialMemberType,
        EmailOptIn,
        EmailOptOut,
        YearsCertified,
        Title,
        FirstName,
        Nickname,
        MiddleName,
        LastName,
        Suffix,
        Salutation,
        InitialMemberDate,
        IndividualsRowEffectiveDate,
        IndividualsRowExpirationDate,
        IndividualsRowChangeReason,
        IndividualsRowStatus
    )
    SELECT
        CAST(individuals_key AS SIGNED),
        CAST(individuals_custom_information_key AS SIGNED),
        CAST(employers_key AS SIGNED),
        CAST(individual_id AS CHAR(6)),
        CAST(full_name AS CHAR(100)),
        CAST(full_name_with_credentials AS CHAR(200)),
        CAST(gender AS CHAR(6)),
        CAST(ethnicity AS CHAR(50)),
        CAST(date_of_birth AS DATE),
        CAST(age AS SIGNED),
        CAST(age_bracket AS CHAR(10)),
        CAST(generation AS CHAR(50)),
        CAST(spouse AS CHAR(25)),
        CAST(home_address AS CHAR(200)),
        CAST(home_city AS CHAR(37)),
        CAST(home_state AS CHAR(2)),
        CAST(home_zip AS CHAR(5)),
        CAST(home_zip_latitude AS DOUBLE),
        CAST(home_zip_longitude AS DOUBLE),
        POINT(
            CAST(home_zip_longitude AS DOUBLE),
            CAST(home_zip_latitude AS DOUBLE)
        ),
        CAST(home_country AS CHAR(37)),
        CAST(home_phone AS CHAR(12)),
        CAST(preferred_address AS CHAR(200)),
        CAST(preferred_city AS CHAR(37)),
        CAST(preferred_state AS CHAR(2)),
        CAST(preferred_zip AS CHAR(5)),
        CAST(preferred_zip_latitude AS DOUBLE),
        CAST(preferred_zip_longitude AS DOUBLE),
        POINT(
            CAST(preferred_zip_longitude AS DOUBLE),
            CAST(preferred_zip_latitude AS DOUBLE)
        ),
        CAST(preferred_country AS CHAR(37)),
        CAST(employer_administrator_yn AS CHAR(3)),
        CAST(house_district AS CHAR(50)),
        CAST(senate_district AS CHAR(50)),
        CAST(congressional_district AS CHAR(50)),
        CAST(mailing_lists AS CHAR),
        CAST(areas_of_expertise_list AS CHAR),
        CAST(fields_of_interest_list AS CHAR),
        CAST(special_needs_list AS CHAR),
        CAST(group_memberships_list AS CHAR),
        CAST(prospective_member_sources_list AS CHAR),
        CAST(sections_list AS CHAR),
        CAST(joined_date AS DATE),
        CAST(secondary_joined_date AS DATE),
        CAST(consecutive_years_of_membership AS SIGNED),
        CAST(cumulative_years_of_membership AS SIGNED),
        CAST(first_individual_contribution_date AS DATE),
        CAST(last_cpe_date AS DATE),
        CAST(in_state_certification_date AS DATE),
        CAST(out_of_state_certification_date AS DATE),
        CAST(original_certification_date AS DATE),
        CAST(reinstatement_date AS DATE),
        CAST(termination_date AS DATE),
        CAST(credentials AS CHAR(25)),
        CAST(position_code AS CHAR(50)),
        CAST(position_description AS CHAR(37)),
        CAST(member_yn AS CHAR(3)),
        CAST(cpa_yn AS CHAR(3)),
        CAST(member_status AS CHAR(50)),
        CAST(member_type AS CHAR(50)),
        CAST(dues_billing_class AS CHAR(50)),
        CAST(actual_chapter AS CHAR(50)),
        CAST(preferred_chapter AS CHAR(50)),
        CAST(email_address AS CHAR(50)),
        CAST(solicitation AS CHAR(50)),
        CAST(certification_status AS CHAR(50)),
        CAST(license_status AS CHAR(50)),
        CAST(peer_review_status AS CHAR(50)),
        CAST(aicpa_member_yn AS CHAR(3)),
        CAST(leader_status AS CHAR(50)),
        CAST(government_office AS CHAR(50)),
        CAST(government_position AS CHAR(50)),
        CAST(government_status AS CHAR(50)),
        CAST(government_district AS CHAR(50)),
        CAST(government_last_year_in_office AS CHAR(4)),
        CAST(government_political_party AS CHAR(50)),
        CAST(volunteer_public_speaking_rating AS CHAR(1)),
        CAST(volunteer_radio_rating AS CHAR(1)),
        CAST(volunteer_special_projects_rating AS CHAR(1)),
        CAST(volunteer_television_rating AS CHAR(1)),
        CAST(volunteer_writing_rating AS CHAR(1)),
        CAST(volunteer_committed_yn AS CHAR(3)),
        CAST(volunteer_verified_yn AS CHAR(3)),
        CAST(volunteer_last_assignment_date AS DATE),
        CAST(volunteer_status AS CHAR(50)),
        CAST(names_control AS CHAR(9)),
        CAST(initial_non_member_type AS CHAR(50)),
        CAST(initial_member_type AS CHAR(50)),
        CAST(email_opt_in AS CHAR),
        CAST(email_opt_out AS CHAR),
        CAST(years_certified AS SIGNED),
        CAST(title AS CHAR(25)),
        CAST(first_name AS CHAR(30)),
        CAST(nickname AS CHAR(30)),
        CAST(middle_name AS CHAR(30)),
        CAST(last_name AS CHAR(30)),
        CAST(suffix AS CHAR(25)),
        CAST(salutation AS CHAR(30)),
        CAST(initial_member_date AS DATE),
        CAST(individuals_row_effective_date AS DATE),
        CAST(individuals_row_expiration_date AS DATE),
        CAST(individuals_row_change_reason AS CHAR),
        CAST(individuals_row_status AS CHAR(10))
    FROM wscpa_amnet.staging_individuals

    ON DUPLICATE KEY UPDATE
        IndividualsCustomInformationKey = VALUES(IndividualsCustomInformationKey),
        EmployersKey = VALUES(EmployersKey),
        IndividualID = VALUES(IndividualID),
        FullName = VALUES(FullName),
        FullNameWithCredentials = VALUES(FullNameWithCredentials),
        Gender = VALUES(Gender),
        Ethnicity = VALUES(Ethnicity),
        DateOfBirth = VALUES(DateOfBirth),
        Age = VALUES(Age),
        AgeBracket = VALUES(AgeBracket),
        Generation = VALUES(Generation),
        Spouse = VALUES(Spouse),
        HomeAddress = VALUES(HomeAddress),
        HomeCity = VALUES(HomeCity),
        HomeState = VALUES(HomeState),
        HomeZIP = VALUES(HomeZIP),
        HomeZIPLatitude = VALUES(HomeZIPLatitude),
        HomeZIPLongitude = VALUES(HomeZIPLongitude),
        HomeZIPGeoLocation = VALUES(HomeZIPGeoLocation),
        HomeCountry = VALUES(HomeCountry),
        HomePhone = VALUES(HomePhone),
        PreferredAddress = VALUES(PreferredAddress),
        PreferredCity = VALUES(PreferredCity),
        PreferredState = VALUES(PreferredState),
        PreferredZIP = VALUES(PreferredZIP),
        PreferredZIPLatitude = VALUES(PreferredZIPLatitude),
        PreferredZIPLongitude = VALUES(PreferredZIPLongitude),
        PreferredZIPGeoLocation = VALUES(PreferredZIPGeoLocation),
        PreferredCountry = VALUES(PreferredCountry),
        EmployerAdministratorYN = VALUES(EmployerAdministratorYN),
        HouseDistrict = VALUES(HouseDistrict),
        SenateDistrict = VALUES(SenateDistrict),
        CongressionalDistrict = VALUES(CongressionalDistrict),
        MailingLists = VALUES(MailingLists),
        AreasOfExpertiseList = VALUES(AreasOfExpertiseList),
        FieldsOfInterestList = VALUES(FieldsOfInterestList),
        SpecialNeedsList = VALUES(SpecialNeedsList),
        GroupMembershipsList = VALUES(GroupMembershipsList),
        ProspectiveMemberSourcesList = VALUES(ProspectiveMemberSourcesList),
        SectionsList = VALUES(SectionsList),
        JoinedDate = VALUES(JoinedDate),
        SecondaryJoinedDate = VALUES(SecondaryJoinedDate),
        ConsecutiveYearsOfMembership = VALUES(ConsecutiveYearsOfMembership),
        CumulativeYearsOfMembership = VALUES(CumulativeYearsOfMembership),
        FirstIndividualContributionDate = VALUES(FirstIndividualContributionDate),
        LastCPEDate = VALUES(LastCPEDate),
        InStateCertificationDate = VALUES(InStateCertificationDate),
        OutOfStateCertificationDate = VALUES(OutOfStateCertificationDate),
        OriginalCertificationDate = VALUES(OriginalCertificationDate),
        ReinstatementDate = VALUES(ReinstatementDate),
        TerminationDate = VALUES(TerminationDate),
        Credentials = VALUES(Credentials),
        PositionCode = VALUES(PositionCode),
        PositionDescription = VALUES(PositionDescription),
        MemberYN = VALUES(MemberYN),
        CPAYN = VALUES(CPAYN),
        MemberStatus = VALUES(MemberStatus),
        MemberType = VALUES(MemberType),
        DuesBillingClass = VALUES(DuesBillingClass),
        ActualChapter = VALUES(ActualChapter),
        PreferredChapter = VALUES(PreferredChapter),
        EmailAddress = VALUES(EmailAddress),
        Solicitation = VALUES(Solicitation),
        CertificationStatus = VALUES(CertificationStatus),
        LicenseStatus = VALUES(LicenseStatus),
        PeerReviewStatus = VALUES(PeerReviewStatus),
        AICPAMemberYN = VALUES(AICPAMemberYN),
        LeaderStatus = VALUES(LeaderStatus),
        GovernmentOffice = VALUES(GovernmentOffice),
        GovernmentPosition = VALUES(GovernmentPosition),
        GovernmentStatus = VALUES(GovernmentStatus),
        GovernmentDistrict = VALUES(GovernmentDistrict),
        GovernmentLastYearInOffice = VALUES(GovernmentLastYearInOffice),
        GovernmentPoliticalParty = VALUES(GovernmentPoliticalParty),
        VolunteerPublicSpeakingRating = VALUES(VolunteerPublicSpeakingRating),
        VolunteerRadioRating = VALUES(VolunteerRadioRating),
        VolunteerSpecialProjectsRating = VALUES(VolunteerSpecialProjectsRating),
        VolunteerTelevisionRating = VALUES(VolunteerTelevisionRating),
        VolunteerWritingRating = VALUES(VolunteerWritingRating),
        VolunteerCommittedYN = VALUES(VolunteerCommittedYN),
        VolunteerVerifiedYN = VALUES(VolunteerVerifiedYN),
        VolunteerLastAssignmentDate = VALUES(VolunteerLastAssignmentDate),
        VolunteerStatus = VALUES(VolunteerStatus),
        NamesControl = VALUES(NamesControl),
        InitialNonMemberType = VALUES(InitialNonMemberType),
        InitialMemberType = VALUES(InitialMemberType),
        EmailOptIn = VALUES(EmailOptIn),
        EmailOptOut = VALUES(EmailOptOut),
        YearsCertified = VALUES(YearsCertified),
        Title = VALUES(Title),
        FirstName = VALUES(FirstName),
        Nickname = VALUES(Nickname),
        MiddleName = VALUES(MiddleName),
        LastName = VALUES(LastName),
        Suffix = VALUES(Suffix),
        Salutation = VALUES(Salutation),
        InitialMemberDate = VALUES(InitialMemberDate),
        IndividualsRowEffectiveDate = VALUES(IndividualsRowEffectiveDate),
        IndividualsRowExpirationDate = VALUES(IndividualsRowExpirationDate),
        IndividualsRowChangeReason = VALUES(IndividualsRowChangeReason),
        IndividualsRowStatus = VALUES(IndividualsRowStatus);

END$$

DELIMITER ;
