DROP PROCEDURE IF EXISTS wscpa_dw.sp_load_dim_individuals;

DELIMITER $$

CREATE PROCEDURE wscpa_dw.sp_load_dim_individuals()
BEGIN

    INSERT INTO wscpa_dw.dim_Individuals
    (
        IndividualsKey,
        IndividualsCustomInformationKey,
        EmployersKey,
        IndividualID,
        FullName,
        FullNameWithCredentials,
        Gender,
        Ethnicity,
        DateOfBirth,
        Age,
        AgeBracket,
        Generation,
        Spouse,
        HomeAddress,
        HomeCity,
        HomeState,
        HomeZIP,
        HomeZIPLatitude,
        HomeZIPLongitude,
        HomeZIPGeoLocation,
        HomeCountry,
        HomePhone,
        PreferredAddress,
        PreferredCity,
        PreferredState,
        PreferredZIP,
        PreferredZIPLatitude,
        PreferredZIPLongitude,
        PreferredZIPGeoLocation,
        PreferredCountry,
        EmployerAdministratorYN,
        HouseDistrict,
        SenateDistrict,
        CongressionalDistrict,
        MailingLists,
        AreasOfExpertiseList,
        FieldsOfInterestList,
        SpecialNeedsList,
        GroupMembershipsList,
        ProspectiveMemberSourcesList,
        SectionsList,
        JoinedDate,
        SecondaryJoinedDate,
        ConsecutiveYearsOfMembership,
        CumulativeYearsOfMembership,
        FirstIndividualContributionDate,
        LastCPEDate,
        InStateCertificationDate,
        OutOfStateCertificationDate,
        OriginalCertificationDate,
        ReinstatementDate,
        TerminationDate,
        Credentials,
        PositionCode,
        PositionDescription,
        MemberYN,
        CPAYN,
        MemberStatus,
        MemberType,
        DuesBillingClass,
        ActualChapter,
        PreferredChapter,
        EmailAddress,
        Solicitation,
        CertificationStatus,
        LicenseStatus,
        PeerReviewStatus,
        AICPAMemberYN,
        LeaderStatus,
        GovernmentOffice,
        GovernmentPosition,
        GovernmentStatus,
        GovernmentDistrict,
        GovernmentLastYearInOffice,
        GovernmentPoliticalParty,
        VolunteerPublicSpeakingRating,
        VolunteerRadioRating,
        VolunteerSpecialProjectsRating,
        VolunteerTelevisionRating,
        VolunteerWritingRating,
        VolunteerCommittedYN,
        VolunteerVerifiedYN,
        VolunteerLastAssignmentDate,
        VolunteerStatus,
        NamesControl,
        InitialNonMemberType,
        InitialMemberType,
        EmailOptIn,
        EmailOptOut,
        YearsCertified,
        Title,
        FirstName,
        Nickname,
        MiddleName,
        LastName,
        Suffix,
        Salutation,
        InitialMemberDate,
        IndividualsRowEffectiveDate,
        IndividualsRowExpirationDate,
        IndividualsRowChangeReason,
        IndividualsRowStatus
    )
    SELECT
        CAST(individuals_key AS SIGNED) AS IndividualsKey,
        CAST(individuals_custom_information_key AS SIGNED) AS IndividualsCustomInformationKey,
        CAST(employers_key AS SIGNED) AS EmployersKey,
        CAST(individual_id AS CHAR(6)) AS IndividualID,
        CAST(full_name AS CHAR(100)) AS FullName,
        CAST(full_name_with_credentials AS CHAR(200)) AS FullNameWithCredentials,
        CAST(gender AS CHAR(6)) AS Gender,
        CAST(ethnicity AS CHAR(50)) AS Ethnicity,
        CAST(date_of_birth AS DATE) AS DateOfBirth,
        CAST(age AS SIGNED) AS Age,
        CAST(age_bracket AS CHAR(10)) AS AgeBracket,
        CAST(generation AS CHAR(50)) AS Generation,
        CAST(spouse AS CHAR(25)) AS Spouse,
        CAST(home_address AS CHAR(200)) AS HomeAddress,
        CAST(home_city AS CHAR(37)) AS HomeCity,
        CAST(home_state AS CHAR(2)) AS HomeState,
        CAST(home_zip AS CHAR(5)) AS HomeZIP,
        CAST(home_zip_latitude AS DOUBLE) AS HomeZIPLatitude,
        CAST(home_zip_longitude AS DOUBLE) AS HomeZIPLongitude,
        POINT(
            CAST(home_zip_longitude AS DOUBLE),
            CAST(home_zip_latitude AS DOUBLE)
        ) AS HomeZIPGeoLocation,
        CAST(home_country AS CHAR(37)) AS HomeCountry,
        CAST(home_phone AS CHAR(12)) AS HomePhone,
        CAST(preferred_address AS CHAR(200)) AS PreferredAddress,
        CAST(preferred_city AS CHAR(37)) AS PreferredCity,
        CAST(preferred_state AS CHAR(2)) AS PreferredState,
        CAST(preferred_zip AS CHAR(5)) AS PreferredZIP,
        CAST(preferred_zip_latitude AS DOUBLE) AS PreferredZIPLatitude,
        CAST(preferred_zip_longitude AS DOUBLE) AS PreferredZIPLongitude,
        POINT(
            CAST(preferred_zip_longitude AS DOUBLE),
            CAST(preferred_zip_latitude AS DOUBLE)
        ) AS PreferredZIPGeoLocation,
        CAST(preferred_country AS CHAR(37)) AS PreferredCountry,
        CAST(employer_administrator_yn AS CHAR(3)) AS EmployerAdministratorYN,
        CAST(house_district AS CHAR(50)) AS HouseDistrict,
        CAST(senate_district AS CHAR(50)) AS SenateDistrict,
        CAST(congressional_district AS CHAR(50)) AS CongressionalDistrict,
        CAST(mailing_lists AS CHAR) AS MailingLists,
        CAST(areas_of_expertise_list AS CHAR) AS AreasOfExpertiseList,
        CAST(fields_of_interest_list AS CHAR) AS FieldsOfInterestList,
        CAST(special_needs_list AS CHAR) AS SpecialNeedsList,
        CAST(group_memberships_list AS CHAR) AS GroupMembershipsList,
        CAST(prospective_member_sources_list AS CHAR) AS ProspectiveMemberSourcesList,
        CAST(sections_list AS CHAR) AS SectionsList,
        CAST(joined_date AS DATE) AS JoinedDate,
        CAST(secondary_joined_date AS DATE) AS SecondaryJoinedDate,
        CAST(consecutive_years_of_membership AS SIGNED) AS ConsecutiveYearsOfMembership,
        CAST(cumulative_years_of_membership AS SIGNED) AS CumulativeYearsOfMembership,
        CAST(first_individual_contribution_date AS DATE) AS FirstIndividualContributionDate,
        CAST(last_cpe_date AS DATE) AS LastCPEDate,
        CAST(in_state_certification_date AS DATE) AS InStateCertificationDate,
        CAST(out_of_state_certification_date AS DATE) AS OutOfStateCertificationDate,
        CAST(original_certification_date AS DATE) AS OriginalCertificationDate,
        CAST(reinstatement_date AS DATE) AS ReinstatementDate,
        CAST(termination_date AS DATE) AS TerminationDate,
        CAST(credentials AS CHAR(25)) AS Credentials,
        CAST(position_code AS CHAR(50)) AS PositionCode,
        CAST(position_description AS CHAR(37)) AS PositionDescription,
        CAST(member_yn AS CHAR(3)) AS MemberYN,
        CAST(cpa_yn AS CHAR(3)) AS CPAYN,
        CAST(member_status AS CHAR(50)) AS MemberStatus,
        CAST(member_type AS CHAR(50)) AS MemberType,
        CAST(dues_billing_class AS CHAR(50)) AS DuesBillingClass,
        CAST(actual_chapter AS CHAR(50)) AS ActualChapter,
        CAST(preferred_chapter AS CHAR(50)) AS PreferredChapter,
        CAST(email_address AS CHAR(50)) AS EmailAddress,
        CAST(solicitation AS CHAR(50)) AS Solicitation,
        CAST(certification_status AS CHAR(50)) AS CertificationStatus,
        CAST(license_status AS CHAR(50)) AS LicenseStatus,
        CAST(peer_review_status AS CHAR(50)) AS PeerReviewStatus,
        CAST(aicpa_member_yn AS CHAR(3)) AS AICPAMemberYN,
        CAST(leader_status AS CHAR(50)) AS LeaderStatus,
        CAST(government_office AS CHAR(50)) AS GovernmentOffice,
        CAST(government_position AS CHAR(50)) AS GovernmentPosition,
        CAST(government_status AS CHAR(50)) AS GovernmentStatus,
        CAST(government_district AS CHAR(50)) AS GovernmentDistrict,
        CAST(government_last_year_in_office AS CHAR(4)) AS GovernmentLastYearInOffice,
        CAST(government_political_party AS CHAR(50)) AS GovernmentPoliticalParty,
        CAST(volunteer_public_speaking_rating AS CHAR(1)) AS VolunteerPublicSpeakingRating,
        CAST(volunteer_radio_rating AS CHAR(1)) AS VolunteerRadioRating,
        CAST(volunteer_special_projects_rating AS CHAR(1)) AS VolunteerSpecialProjectsRating,
        CAST(volunteer_television_rating AS CHAR(1)) AS VolunteerTelevisionRating,
        CAST(volunteer_writing_rating AS CHAR(1)) AS VolunteerWritingRating,
        CAST(volunteer_committed_yn AS CHAR(3)) AS VolunteerCommittedYN,
        CAST(volunteer_verified_yn AS CHAR(3)) AS VolunteerVerifiedYN,
        CAST(volunteer_last_assignment_date AS DATE) AS VolunteerLastAssignmentDate,
        CAST(volunteer_status AS CHAR(50)) AS VolunteerStatus,
        CAST(names_control AS CHAR(9)) AS NamesControl,
        CAST(initial_non_member_type AS CHAR(50)) AS InitialNonMemberType,
        CAST(initial_member_type AS CHAR(50)) AS InitialMemberType,
        CAST(email_opt_in AS CHAR) AS EmailOptIn,
        CAST(email_opt_out AS CHAR) AS EmailOptOut,
        CAST(years_certified AS SIGNED) AS YearsCertified,
        CAST(title AS CHAR(25)) AS Title,
        CAST(first_name AS CHAR(30)) AS FirstName,
        CAST(nickname AS CHAR(30)) AS Nickname,
        CAST(middle_name AS CHAR(30)) AS MiddleName,
        CAST(last_name AS CHAR(30)) AS LastName,
        CAST(suffix AS CHAR(25)) AS Suffix,
        CAST(salutation AS CHAR(30)) AS Salutation,
        CAST(initial_member_date AS DATE) AS InitialMemberDate,
        CAST(individuals_row_effective_date AS DATE) AS IndividualsRowEffectiveDate,
        CAST(individuals_row_expiration_date AS DATE) AS IndividualsRowExpirationDate,
        CAST(individuals_row_change_reason AS CHAR) AS IndividualsRowChangeReason,
        CAST(individuals_row_status AS CHAR(10)) AS IndividualsRowStatus
    FROM wscpa_amnet.staging_individuals

    ) AS src

    ON DUPLICATE KEY UPDATE
        IndividualsCustomInformationKey = src.IndividualsCustomInformationKey,
        EmployersKey = src.EmployersKey,
        IndividualID = src.IndividualID,
        FullName = src.FullName,
        FullNameWithCredentials = src.FullNameWithCredentials,
        Gender = src.Gender,
        Ethnicity = src.Ethnicity,
        DateOfBirth = src.DateOfBirth,
        Age = src.Age,
        AgeBracket = src.AgeBracket,
        Generation = src.Generation,
        Spouse = src.Spouse,
        HomeAddress = src.HomeAddress,
        HomeCity = src.HomeCity,
        HomeState = src.HomeState,
        HomeZIP = src.HomeZIP,
        HomeZIPLatitude = src.HomeZIPLatitude,
        HomeZIPLongitude = src.HomeZIPLongitude,
        HomeZIPGeoLocation = src.HomeZIPGeoLocation,
        HomeCountry = src.HomeCountry,
        HomePhone = src.HomePhone,
        PreferredAddress = src.PreferredAddress,
        PreferredCity = src.PreferredCity,
        PreferredState = src.PreferredState,
        PreferredZIP = src.PreferredZIP,
        PreferredZIPLatitude = src.PreferredZIPLatitude,
        PreferredZIPLongitude = src.PreferredZIPLongitude,
        PreferredZIPGeoLocation = src.PreferredZIPGeoLocation,
        PreferredCountry = src.PreferredCountry,
        EmployerAdministratorYN = src.EmployerAdministratorYN,
        HouseDistrict = src.HouseDistrict,
        SenateDistrict = src.SenateDistrict,
        CongressionalDistrict = src.CongressionalDistrict,
        MailingLists = src.MailingLists,
        AreasOfExpertiseList = src.AreasOfExpertiseList,
        FieldsOfInterestList = src.FieldsOfInterestList,
        SpecialNeedsList = src.SpecialNeedsList,
        GroupMembershipsList = src.GroupMembershipsList,
        ProspectiveMemberSourcesList = src.ProspectiveMemberSourcesList,
        SectionsList = src.SectionsList,
        JoinedDate = src.JoinedDate,
        SecondaryJoinedDate = src.SecondaryJoinedDate,
        ConsecutiveYearsOfMembership = src.ConsecutiveYearsOfMembership,
        CumulativeYearsOfMembership = src.CumulativeYearsOfMembership,
        FirstIndividualContributionDate = src.FirstIndividualContributionDate,
        LastCPEDate = src.LastCPEDate,
        InStateCertificationDate = src.InStateCertificationDate,
        OutOfStateCertificationDate = src.OutOfStateCertificationDate,
        OriginalCertificationDate = src.OriginalCertificationDate,
        ReinstatementDate = src.ReinstatementDate,
        TerminationDate = src.TerminationDate,
        Credentials = src.Credentials,
        PositionCode = src.PositionCode,
        PositionDescription = src.PositionDescription,
        MemberYN = src.MemberYN,
        CPAYN = src.CPAYN,
        MemberStatus = src.MemberStatus,
        MemberType = src.MemberType,
        DuesBillingClass = src.DuesBillingClass,
        ActualChapter = src.ActualChapter,
        PreferredChapter = src.PreferredChapter,
        EmailAddress = src.EmailAddress,
        Solicitation = src.Solicitation,
        CertificationStatus = src.CertificationStatus,
        LicenseStatus = src.LicenseStatus,
        PeerReviewStatus = src.PeerReviewStatus,
        AICPAMemberYN = src.AICPAMemberYN,
        LeaderStatus = src.LeaderStatus,
        GovernmentOffice = src.GovernmentOffice,
        GovernmentPosition = src.GovernmentPosition,
        GovernmentStatus = src.GovernmentStatus,
        GovernmentDistrict = src.GovernmentDistrict,
        GovernmentLastYearInOffice = src.GovernmentLastYearInOffice,
        GovernmentPoliticalParty = src.GovernmentPoliticalParty,
        VolunteerPublicSpeakingRating = src.VolunteerPublicSpeakingRating,
        VolunteerRadioRating = src.VolunteerRadioRating,
        VolunteerSpecialProjectsRating = src.VolunteerSpecialProjectsRating,
        VolunteerTelevisionRating = src.VolunteerTelevisionRating,
        VolunteerWritingRating = src.VolunteerWritingRating,
        VolunteerCommittedYN = src.VolunteerCommittedYN,
        VolunteerVerifiedYN = src.VolunteerVerifiedYN,
        VolunteerLastAssignmentDate = src.VolunteerLastAssignmentDate,
        VolunteerStatus = src.VolunteerStatus,
        NamesControl = src.NamesControl,
        InitialNonMemberType = src.InitialNonMemberType,
        InitialMemberType = src.InitialMemberType,
        EmailOptIn = src.EmailOptIn,
        EmailOptOut = src.EmailOptOut,
        YearsCertified = src.YearsCertified,
        Title = src.Title,
        FirstName = src.FirstName,
        Nickname = src.Nickname,
        MiddleName = src.MiddleName,
        LastName = src.LastName,
        Suffix = src.Suffix,
        Salutation = src.Salutation,
        InitialMemberDate = src.InitialMemberDate,
        IndividualsRowEffectiveDate = src.IndividualsRowEffectiveDate,
        IndividualsRowExpirationDate = src.IndividualsRowExpirationDate,
        IndividualsRowChangeReason = src.IndividualsRowChangeReason,
        IndividualsRowStatus = src.IndividualsRowStatus;

END$$

DELIMITER ;
