DROP PROCEDURE IF EXISTS wscpa_dw.sp_load_dim_firms;

DELIMITER $$

CREATE PROCEDURE wscpa_dw.sp_load_dim_firms()
BEGIN

    INSERT INTO wscpa_dw.dim_Firms
    (
        FirmsKey,
        FirmsCustomInformationKey,
        MainOfficesKey,
        ExhibitorPrimaryContactsKey,
        ExhibitorEmergencyContactsKey,
        PersonsInChargeKey,
        FirmCode,
        FirmName,
        FirmAddress,
        FirmCity,
        FirmState,
        FirmZIP,
        FirmZIPLatitude,
        FirmZIPLongitude,
        FirmZIPGeoLocation,
        FirmChapter,
        FirmCounty,
        FirmCountry,
        AICPANumber,
        ReviewBillingClass,
        GroupMembershipYN,
        GeneralBusinessType,
        SpecificBusinessType,
        EntityType,
        FirstFirmContributionDate,
        CompanyHeldPubliclyYN,
        PersonInCharge,
        FirmPaysDuesYN,
        RevenueRange,
        ClientReferralStatus,
        ClientReferralChapterList,
        ClientReferralServiceList,
        ClientReferralCityList,
        ClientReferralIndustryList,
        MediaCirculation,
        MediaFormat,
        MediaFrequency,
        MediaGeneralType,
        MediaSpecificType,
        ReviewStatus,
        ReviewDivision,
        ReviewLocation,
        ReviewType,
        ReviewSource,
        LastReviewDate,
        NextReviewDate,
        ExhibitorYearExhibiting,
        ExhibitorStatus,
        ExhibitorProductTypesList,
        ExhibitorTypesList,
        ExhibitorOtherList,
        FirmsRowEffectiveDate,
        FirmsRowExpirationDate,
        FirmsRowChangeReason,
        FirmsRowStatus
    )
    SELECT
        CAST(firms_key AS SIGNED) AS FirmsKey,
        CAST(firms_custom_information_key AS SIGNED) AS FirmsCustomInformationKey,
        CAST(main_offices_key AS SIGNED) AS MainOfficesKey,
        CAST(exhibitor_primary_contacts_key AS SIGNED) AS ExhibitorPrimaryContactsKey,
        CAST(exhibitor_emergency_contacts_key AS SIGNED) AS ExhibitorEmergencyContactsKey,
        CAST(persons_in_charge_key AS SIGNED) AS PersonsInChargeKey,
        CAST(firm_code AS CHAR(5)) AS FirmCode,
        CAST(firm_name AS CHAR(75)) AS FirmName,
        CAST(firm_address AS CHAR(37)) AS FirmAddress,
        CAST(firm_city AS CHAR(37)) AS FirmCity,
        CAST(firm_state AS CHAR(2)) AS FirmState,
        CAST(firm_zip AS CHAR(5)) AS FirmZIP,
        CAST(firm_zip_latitude AS DOUBLE) AS FirmZIPLatitude,
        CAST(firm_zip_longitude AS DOUBLE) AS FirmZIPLongitude,
        POINT(
            CAST(firm_zip_longitude AS DOUBLE),
            CAST(firm_zip_latitude AS DOUBLE)
        ) AS FirmZIPGeoLocation,
        CAST(firm_chapter AS CHAR(50)) AS FirmChapter,
        CAST(firm_county AS CHAR(50)) AS FirmCounty,
        CAST(firm_country AS CHAR(37)) AS FirmCountry,
        CAST(aicpa_number AS CHAR(12)) AS AICPANumber,
        CAST(review_billing_class AS CHAR(3)) AS ReviewBillingClass,
        CAST(group_membership_yn AS CHAR(3)) AS GroupMembershipYN,
        CAST(general_business_type AS CHAR(50)) AS GeneralBusinessType,
        CAST(specific_business_type AS CHAR(50)) AS SpecificBusinessType,
        CAST(entity_type AS CHAR(50)) AS EntityType,
        CAST(first_firm_contribution_date AS DATE) AS FirstFirmContributionDate,
        CAST(company_held_publicly_yn AS CHAR(3)) AS CompanyHeldPubliclyYN,
        CAST(person_in_charge AS CHAR(37)) AS PersonInCharge,
        CAST(firm_pays_dues_yn AS CHAR(3)) AS FirmPaysDuesYN,
        CAST(revenue_range AS CHAR(50)) AS RevenueRange,
        CAST(client_referral_status AS CHAR(10)) AS ClientReferralStatus,
        CAST(client_referral_chapter_list AS CHAR) AS ClientReferralChapterList,
        CAST(client_referral_service_list AS CHAR) AS ClientReferralServiceList,
        CAST(client_referral_city_list AS CHAR) AS ClientReferralCityList,
        CAST(client_referral_industry_list AS CHAR) AS ClientReferralIndustryList,
        CAST(media_circulation AS SIGNED) AS MediaCirculation,
        CAST(media_format AS CHAR(50)) AS MediaFormat,
        CAST(media_frequency AS CHAR(50)) AS MediaFrequency,
        CAST(media_general_type AS CHAR(50)) AS MediaGeneralType,
        CAST(media_specific_type AS CHAR(50)) AS MediaSpecificType,
        CAST(review_status AS CHAR(50)) AS ReviewStatus,
        CAST(review_division AS CHAR(50)) AS ReviewDivision,
        CAST(review_location AS CHAR(50)) AS ReviewLocation,
        CAST(review_type AS CHAR(50)) AS ReviewType,
        CAST(review_source AS CHAR(50)) AS ReviewSource,
        CAST(last_review_date AS DATE) AS LastReviewDate,
        CAST(next_review_date AS DATE) AS NextReviewDate,
        CAST(exhibitor_year_exhibiting AS CHAR(4)) AS ExhibitorYearExhibiting,
        CAST(exhibitor_status AS CHAR(50)) AS ExhibitorStatus,
        CAST(exhibitor_product_types_list AS CHAR) AS ExhibitorProductTypesList,
        CAST(exhibitor_types_list AS CHAR) AS ExhibitorTypesList,
        CAST(exhibitor_other_list AS CHAR) AS ExhibitorOtherList,
        CAST(firms_row_effective_date AS DATETIME) AS FirmsRowEffectiveDate,
        CAST(firms_row_expiration_date AS DATETIME) AS FirmsRowExpirationDate,
        CAST(firms_row_change_reason AS CHAR) AS FirmsRowChangeReason,
        CAST(firms_row_status AS CHAR(10)) AS FirmsRowStatus
    FROM wscpa_amnet.staging_firms

    ) AS src

    ON DUPLICATE KEY UPDATE
        FirmsCustomInformationKey = src.FirmsCustomInformationKey,
        MainOfficesKey = src.MainOfficesKey,
        ExhibitorPrimaryContactsKey = src.ExhibitorPrimaryContactsKey,
        ExhibitorEmergencyContactsKey = src.ExhibitorEmergencyContactsKey,
        PersonsInChargeKey = src.PersonsInChargeKey,
        FirmCode = src.FirmCode,
        FirmName = src.FirmName,
        FirmAddress = src.FirmAddress,
        FirmCity = src.FirmCity,
        FirmState = src.FirmState,
        FirmZIP = src.FirmZIP,
        FirmZIPLatitude = src.FirmZIPLatitude,
        FirmZIPLongitude = src.FirmZIPLongitude,
        FirmZIPGeoLocation = src.FirmZIPGeoLocation,
        FirmChapter = src.FirmChapter,
        FirmCounty = src.FirmCounty,
        FirmCountry = src.FirmCountry,
        AICPANumber = src.AICPANumber,
        ReviewBillingClass = src.ReviewBillingClass,
        GroupMembershipYN = src.GroupMembershipYN,
        GeneralBusinessType = src.GeneralBusinessType,
        SpecificBusinessType = src.SpecificBusinessType,
        EntityType = src.EntityType,
        FirstFirmContributionDate = src.FirstFirmContributionDate,
        CompanyHeldPubliclyYN = src.CompanyHeldPubliclyYN,
        PersonInCharge = src.PersonInCharge,
        FirmPaysDuesYN = src.FirmPaysDuesYN,
        RevenueRange = src.RevenueRange,
        ClientReferralStatus = src.ClientReferralStatus,
        ClientReferralChapterList = src.ClientReferralChapterList,
        ClientReferralServiceList = src.ClientReferralServiceList,
        ClientReferralCityList = src.ClientReferralCityList,
        ClientReferralIndustryList = src.ClientReferralIndustryList,
        MediaCirculation = src.MediaCirculation,
        MediaFormat = src.MediaFormat,
        MediaFrequency = src.MediaFrequency,
        MediaGeneralType = src.MediaGeneralType,
        MediaSpecificType = src.MediaSpecificType,
        ReviewStatus = src.ReviewStatus,
        ReviewDivision = src.ReviewDivision,
        ReviewLocation = src.ReviewLocation,
        ReviewType = src.ReviewType,
        ReviewSource = src.ReviewSource,
        LastReviewDate = src.LastReviewDate,
        NextReviewDate = src.NextReviewDate,
        ExhibitorYearExhibiting = src.ExhibitorYearExhibiting,
        ExhibitorStatus = src.ExhibitorStatus,
        ExhibitorProductTypesList = src.ExhibitorProductTypesList,
        ExhibitorTypesList = src.ExhibitorTypesList,
        ExhibitorOtherList = src.ExhibitorOtherList,
        FirmsRowEffectiveDate = src.FirmsRowEffectiveDate,
        FirmsRowExpirationDate = src.FirmsRowExpirationDate,
        FirmsRowChangeReason = src.FirmsRowChangeReason,
        FirmsRowStatus = src.FirmsRowStatus;

END$$

DELIMITER ;
