DROP TABLE IF EXISTS wscpa_amnet.staging_dues_year_individual_snapshots;

CREATE TABLE wscpa_amnet.staging_dues_year_individual_snapshots (
    dues_years_key INT,
    individuals_key INT,
    employers_key INT,
    prior_dues_year_data_key INT,
    member_status_change_reasons_key INT,
    dues_billing_types_key INT,
    individual_id VARCHAR(20),
    dy_age VARCHAR(100),
    dy_age_bracket VARCHAR(32),
    dy_member_change_count INT,
    dy_member_status_change_count INT,
    dy_billing_class_change_count INT,
    dy_credit_hours_earned VARCHAR(100),
    dy_billing_date VARCHAR(255),
    dy_last_invoice_date VARCHAR(255),
    dy_last_payment_date VARCHAR(255),
    dy_dues_gross_billing VARCHAR(100),
    dy_dues_adjustments VARCHAR(100),
    dy_dues_net_billing VARCHAR(100),
    dy_dues_gross_payments VARCHAR(100),
    dy_dues_refunds VARCHAR(100),
    dy_dues_net_payments VARCHAR(100),
    dy_dues_balance VARCHAR(100),
    dy_chapter_dues VARCHAR(100),
    dy_contribution_total VARCHAR(100),
    dy_contribution_count INT,
    dy_committee_membership_count INT,
    dy_committee_attendance_count INT,
    dy_event_fee_total VARCHAR(100),
    dy_event_payment_total VARCHAR(100),
    dy_event_registration_count INT,
    dy_product_sales_quantity INT,
    dy_product_extended_net_price_total VARCHAR(100),
    dy_product_extended_item_cost_total VARCHAR(100),
    dy_product_margin VARCHAR(100),
    dy_event_attendance_count INT,
    dy_volunteer_assignment_count INT,
    dy_years_certified INT,
    dy_consecutive_years_of_membership INT,
    dy_cumulative_years_of_membership INT,
    dy_initial_billing_class VARCHAR(128),
    dy_initial_member_type VARCHAR(128),
    load_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
