DROP TABLE IF EXISTS wscpa_amnet.staging_events;

CREATE TABLE wscpa_amnet.staging_events (
  events_key INT NOT NULL,
  events_custom_information_key INT DEFAULT NULL,
  begin_dates_key CHAR(25) DEFAULT NULL,
  end_dates_key CHAR(25) DEFAULT NULL,
  accounting_close_dates_key CHAR(25) DEFAULT NULL,
  facilities_key INT DEFAULT NULL,
  primary_vendors_key INT DEFAULT NULL,
  primary_administrators_key INT DEFAULT NULL,
  staff_contacts_key INT DEFAULT NULL,
  event_codeyr VARCHAR(32) DEFAULT NULL,
  event_code_1 VARCHAR(64) DEFAULT NULL,
  event_code_2 VARCHAR(64) DEFAULT NULL,
  event_name VARCHAR(512) DEFAULT NULL,
  extended_event_title VARCHAR(1024) DEFAULT NULL,
  event_status VARCHAR(64) DEFAULT NULL,
  cancellation_date VARCHAR(255) DEFAULT NULL,
  event_has_sessions_yn VARCHAR(25) DEFAULT NULL,
  unique_event_yn VARCHAR(25) DEFAULT NULL,
  new_event_yn VARCHAR(25) DEFAULT NULL,
  exclude_from_catalog_yn VARCHAR(25) DEFAULT NULL,
  event_scope VARCHAR(64) DEFAULT NULL,
  event_level VARCHAR(64) DEFAULT NULL,
  event_city VARCHAR(128) DEFAULT NULL,
  event_company VARCHAR(128) DEFAULT NULL,
  event_division VARCHAR(128) DEFAULT NULL,
  event_gl_account VARCHAR(64) DEFAULT NULL,
  national_acronym VARCHAR(64) DEFAULT NULL,
  yellowbook_event_yn VARCHAR(25) DEFAULT NULL,
  attest_and_compilation_event_yn VARCHAR(25) DEFAULT NULL,
  certified_financial_planner_event_yn VARCHAR(25) DEFAULT NULL,
  nasba_certified_event_yn VARCHAR(25) DEFAULT NULL,
  event_vendor_code_1 VARCHAR(64) DEFAULT NULL,
  event_vendor_code_2 VARCHAR(64) DEFAULT NULL,
  event_fields_of_study_list VARCHAR(512) DEFAULT NULL,
  event_fields_of_interest_list VARCHAR(512) DEFAULT NULL,
  event_formats_list VARCHAR(128) DEFAULT NULL,
  event_topics_list VARCHAR(512) DEFAULT NULL,
  load_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (events_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
