DROP TABLE IF EXISTS wscpa_amnet.staging_calendar_month_individual_snapshots;

CREATE TABLE wscpa_amnet.staging_calendar_month_individual_snapshots (
    months_key INT,
    individuals_key INT,
    employers_key INT,
    prior_month_data_key INT,
    prior_dues_year_data_key INT,
    member_status_change_reasons_key INT,
    individual_id VARCHAR(20),
    cm_age VARCHAR(25),
    cm_age_bracket VARCHAR(32),
    cm_member_change_count INT,
    cm_member_status_change_count INT,
    cm_billing_class_change_count INT,
    cm_credit_hours_earned DECIMAL(6,2),
    cm_dues_gross_billing DECIMAL(19,4),
    cm_dues_adjustments DECIMAL(19,4),
    cm_dues_net_billing DECIMAL(19,4),
    cm_dues_gross_payments DECIMAL(19,4),
    cm_dues_refunds DECIMAL(19,4),
    cm_dues_net_payments DECIMAL(19,4),
    cm_contribution_total DECIMAL(19,4),
    cm_contribution_count INT,
    cm_committee_membership_count INT,
    cm_committee_attendance_count INT,
    cm_event_fee_total DECIMAL(19,4),
    cm_event_payment_total DECIMAL(19,4),
    cm_event_registration_count INT,
    cm_event_attendance_count INT,
    cm_product_sales_quantity INT,
    cm_product_extended_net_price_total DECIMAL(19,4),
    cm_product_extended_item_cost_total DECIMAL(19,4),
    cm_product_margin DECIMAL(19,4),
    cm_volunteer_assignment_count INT,
    cm_months_certified INT,
    load_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
