DROP TABLE IF EXISTS wscpa_amnet.staging_dates;

CREATE TABLE wscpa_amnet.staging_dates (
    dates_key VARCHAR(20) PRIMARY KEY,
    date VARCHAR(255),
    full_date DATE,
    calendar_year INTEGER,
    calendar_year_and_quarter VARCHAR(32),
    calendar_quarter INTEGER,
    calendar_year_and_month VARCHAR(32),
    calendar_month_number INTEGER,
    calendar_month_name VARCHAR(32),
    calendar_month_abbreviation VARCHAR(16),
    week_of_the_calendar_year INTEGER,
    iso_week_of_the_year INTEGER,
    week_of_the_month INTEGER,
    day_of_the_calendar_year INTEGER,
    day_of_the_month INTEGER,
    day_of_the_month_ordinal VARCHAR(16),
    day_of_the_week INTEGER,
    day_of_the_week_name VARCHAR(32),
    day_type VARCHAR(32),
    holiday_name VARCHAR(128),
    dues_year_begin_date VARCHAR(255),
    dues_year_end_date VARCHAR(255),
    dues_year_name VARCHAR(32),
    dues_year_and_quarter VARCHAR(32),
    dues_quarter INTEGER,
    dues_year_and_period VARCHAR(32),
    dues_period INTEGER,
    week_of_the_dues_year INTEGER,
    day_of_the_dues_year INTEGER,
    event_year_begin_date VARCHAR(255),
    event_year_end_date VARCHAR(255),
    event_year_name VARCHAR(32),
    event_year_and_quarter VARCHAR(32),
    event_quarter INTEGER,
    event_year_and_period VARCHAR(32),
    event_period INTEGER,
    week_of_the_event_year INTEGER,
    day_of_the_event_year INTEGER,
    accounting_year_begin_date VARCHAR(255),
    accounting_year_end_date VARCHAR(255),
    accounting_year_name VARCHAR(32),
    accounting_year_and_quarter VARCHAR(32),
    accounting_quarter INTEGER,
    accounting_year_and_period VARCHAR(32),
    accounting_period INTEGER,
    week_of_the_accounting_year INTEGER,
    day_of_the_accounting_year INTEGER,
    period_counter INTEGER,
    load_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
