DROP TABLE IF EXISTS wscpa_amnet.staging_firms;

CREATE TABLE wscpa_amnet.staging_firms (
    firms_key VARCHAR(20) PRIMARY KEY,
    firms_custom_information_key VARCHAR(20),
    main_offices_key VARCHAR(20),
    firm_code VARCHAR(20),
    firm_name VARCHAR(255),
    firm_address VARCHAR(255),
    firm_city VARCHAR(128),
    firm_state VARCHAR(20),
    firm_zip VARCHAR(20),
    firm_zip_latitude VARCHAR(50),
    firm_zip_longitude VARCHAR(50),
    firm_zip_geolocation VARCHAR(255),
    firm_chapter VARCHAR(128),
    firm_county VARCHAR(128),
    firm_country VARCHAR(128),
    general_business_type VARCHAR(128),
    specific_business_type VARCHAR(128),
    entity_type VARCHAR(128),
    first_firm_contribution_date VARCHAR(255),
    company_held_publicly_yn VARCHAR(10),
    person_in_charge VARCHAR(255),
    firm_pays_dues_yn VARCHAR(10),
    revenue_range VARCHAR(128),
    client_referral_status VARCHAR(128),
    client_referral_chapter_list VARCHAR(2000),
    client_referral_service_list VARCHAR(2000),
    client_referral_city_list VARCHAR(2000),
    client_referral_industry_list VARCHAR(2000),
    media_circulation VARCHAR(50),
    media_format VARCHAR(128),
    media_frequency VARCHAR(128),
    media_general_type VARCHAR(128),
    media_specific_type VARCHAR(128),
    review_status VARCHAR(128),
    review_division VARCHAR(128),
    review_location VARCHAR(128),
    review_type VARCHAR(128),
    review_source VARCHAR(128),
    last_review_date VARCHAR(255),
    next_review_date VARCHAR(255),
    firms_row_effective_date VARCHAR(255),
    firms_row_expiration_date VARCHAR(255),
    firms_row_change_reason VARCHAR(2000),
    firms_row_status VARCHAR(128),
    exhibitor_primary_contacts_key VARCHAR(20),
    exhibitor_emergency_contacts_key VARCHAR(20),
    exhibitor_year_exhibiting VARCHAR(20),
    exhibitor_status VARCHAR(128),
    exhibitor_product_types_list VARCHAR(2000),
    exhibitor_types_list VARCHAR(2000),
    exhibitor_other_list VARCHAR(2000),
    persons_in_charge_key VARCHAR(20),
    review_billing_class VARCHAR(128),
    aicpa_number VARCHAR(20),
    group_membership_yn VARCHAR(10),
    load_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
