DROP TABLE IF EXISTS wscpa_dw.breezio_users;

CREATE TABLE wscpa_dw.breezio_users
(
    id                      BIGINT UNSIGNED PRIMARY KEY,
    unverified_email        VARCHAR(255),
    username                VARCHAR(255),
    role                    VARCHAR(100),
    first_name              VARCHAR(255),
    last_name               VARCHAR(255),
    status                  VARCHAR(100),
    state                   INT UNSIGNED,
    image_path              TEXT,
    cv_path                 TEXT,
    is_deleted              TINYINT UNSIGNED,
    is_featured             TINYINT UNSIGNED,
    birthdate               DATE,
    creation_date           DATETIME,
    last_modified_by        BIGINT UNSIGNED,
    modified_date           DATETIME,
    bio                     TEXT,
    short_bio               TEXT,
    gender                  VARCHAR(100),
    website                 VARCHAR(500),
    office_hours            VARCHAR(255),
    view_count              INT UNSIGNED,
    posts_count             INT UNSIGNED,
    comments_count          INT UNSIGNED,
    votes_count             INT UNSIGNED,
    score                   INT,
    foo                     INT,
    bar                     INT,
    active_key              VARCHAR(255),
    title                   VARCHAR(500),
    version                 INT UNSIGNED,
    invited_by              BIGINT UNSIGNED,
    invited_count           INT UNSIGNED,
    portal_id               BIGINT UNSIGNED,
    original_portal_id      BIGINT UNSIGNED,
    external_id             BIGINT UNSIGNED,
    external_id2            BIGINT UNSIGNED,
    root_folder_id          VARCHAR(255),
    is_private              TINYINT UNSIGNED,
    cloak_mode              INT UNSIGNED,
    privacy                 VARCHAR(100),
    metadata_company        VARCHAR(500),
    metadata_city           VARCHAR(255),
    metadata_country        VARCHAR(255),
    metadata_phone          VARCHAR(100),
    metadata_twitter        VARCHAR(500),
    metadata_facebook       VARCHAR(500),
    metadata_linkedin       VARCHAR(500),
    metadata_instagram      VARCHAR(500),
    metadata_public_email   VARCHAR(255),
    metadata_nickname       VARCHAR(255),
    metadata_json           JSON,
    timezone                VARCHAR(100),
    user_type               VARCHAR(100),
    membership_type         VARCHAR(100),
    last_fetch_date         DATETIME,
    last_seen_date          DATETIME,
    followers_count         INT UNSIGNED,
    followings_count        INT UNSIGNED,
    is_active               TINYINT UNSIGNED,
    hard_deleted            TINYINT UNSIGNED,
    sync_required           TINYINT UNSIGNED,
    last_sync_date          DATETIME,
    last_sync_by            BIGINT UNSIGNED,
    is_suspended            TINYINT UNSIGNED,
    alternate_email         VARCHAR(255),
    hash                    VARCHAR(255),
    user_email              VARCHAR(255),
    entity_type             VARCHAR(100),
    entity_name             VARCHAR(100)
) ENGINE=InnoDB;
