DROP TABLE IF EXISTS wscpa_dw.breezio_organizations;

CREATE TABLE wscpa_dw.breezio_organizations
(
    id                          BIGINT UNSIGNED PRIMARY KEY,
    user_id                     BIGINT UNSIGNED,
    name                        VARCHAR(500),
    category                    VARCHAR(255),
    region                      VARCHAR(255),
    bio                         TEXT,
    billing_email               VARCHAR(255),
    website                     VARCHAR(500),
    image_path                  TEXT,
    background_image_path       TEXT,
    slug                        VARCHAR(500),
    foo                         INT,
    view_count                  INT UNSIGNED,
    creation_date               DATETIME,
    modified_date               DATETIME,
    is_featured                 TINYINT UNSIGNED,
    is_deleted                  TINYINT UNSIGNED,
    portal_id                   BIGINT UNSIGNED,
    root_folder_id              VARCHAR(255),
    is_private                  TINYINT UNSIGNED,
    external_id                 VARCHAR(255),
    external_id2                VARCHAR(255),
    latest_posts                INT UNSIGNED,
    latest_paths                INT UNSIGNED,
    post_force_subscription     TINYINT UNSIGNED,
    quick_discussion            TINYINT UNSIGNED,
    community_members           TINYINT UNSIGNED,
    visibility                  TINYINT UNSIGNED,
    event_button_visibility     TINYINT UNSIGNED,
    video_conference            TINYINT UNSIGNED,
    join_rule                   VARCHAR(100),
    default_role                VARCHAR(100),
    config_json                 JSON,
    entity_type                 VARCHAR(100),
    entity_name                 VARCHAR(100),
    user_json                   JSON
) ENGINE=InnoDB;
