SELECT
  CAST(json_data->>'$.id' AS UNSIGNED)                     AS id,
  json_data->>'$.unverifiedEmail'                          AS unverified_email,
  json_data->>'$.username'                                 AS username,
  json_data->>'$.role'                                     AS role,
  json_data->>'$.firstName'                                AS first_name,
  json_data->>'$.lastName'                                 AS last_name,
  json_data->>'$.status'                                   AS status,
  CAST(json_data->>'$.state' AS UNSIGNED)                  AS state,
  json_data->>'$.imagePath'                                AS image_path,
  NULLIF(json_data->>'$.cvPath','')                        AS cv_path,
  CAST(json_data->>'$.deleted' AS UNSIGNED)                AS is_deleted,
  CAST(json_data->>'$.featured' AS UNSIGNED)               AS is_featured,
  STR_TO_DATE(json_data->>'$.birthdate', '%Y-%m-%d')       AS birthdate,
  STR_TO_DATE(json_data->>'$.creationDate', '%Y-%m-%dT%H:%i:%s') AS creation_date,
  CAST(json_data->>'$.lastModifiedBy' AS UNSIGNED)         AS last_modified_by,
  STR_TO_DATE(json_data->>'$.modifiedDate', '%Y-%m-%dT%H:%i:%s') AS modified_date,
  NULLIF(json_data->>'$.bio','')                           AS bio,
  NULLIF(json_data->>'$.shortBio','')                      AS short_bio,
  NULLIF(json_data->>'$.gender','')                        AS gender,
  NULLIF(json_data->>'$.website','')                       AS website,
  NULLIF(json_data->>'$.officeHours','')                   AS office_hours,
  CAST(json_data->>'$.viewCount' AS UNSIGNED)              AS view_count,
  CAST(json_data->>'$.postsCount' AS UNSIGNED)             AS posts_count,
  CAST(json_data->>'$.commentsCount' AS UNSIGNED)          AS comments_count,
  CAST(json_data->>'$.votesCount' AS UNSIGNED)             AS votes_count,
  CAST(json_data->>'$.score' AS SIGNED)                    AS score,
  CAST(json_data->>'$.foo' AS SIGNED)                      AS foo,
  CAST(json_data->>'$.bar' AS SIGNED)                      AS bar,
  json_data->>'$.activeKey'                                AS active_key,
  NULLIF(json_data->>'$.title','')                         AS title,
  CAST(json_data->>'$.version' AS UNSIGNED)                AS version,
  CAST(json_data->>'$.invitedBy' AS UNSIGNED)              AS invited_by,
  CAST(json_data->>'$.invitedCount' AS UNSIGNED)           AS invited_count,
  CAST(json_data->>'$.portalId' AS UNSIGNED)               AS portal_id,
  CAST(json_data->>'$.originalPortalId' AS UNSIGNED)       AS original_portal_id,
  CAST(json_data->>'$.externalId' AS UNSIGNED)             AS external_id,
  CAST(json_data->>'$.externalId2' AS UNSIGNED)            AS external_id2,
  json_data->>'$.rootFolderId'                             AS root_folder_id,
  CAST(json_data->>'$.private' AS UNSIGNED)                AS is_private,
  CAST(json_data->>'$.cloakMode' AS UNSIGNED)              AS cloak_mode,
  json_data->>'$.privacy'                                  AS privacy,
  NULLIF(json_data->>'$.metadata.company','')              AS metadata_company,
  NULLIF(json_data->>'$.metadata.city','')                 AS metadata_city,
  NULLIF(json_data->>'$.metadata.country','')              AS metadata_country,
  NULLIF(json_data->>'$.metadata.phone','')                AS metadata_phone,
  NULLIF(json_data->>'$.metadata.twitter','')              AS metadata_twitter,
  NULLIF(json_data->>'$.metadata.facebook','')             AS metadata_facebook,
  NULLIF(json_data->>'$.metadata.linkedin','')             AS metadata_linkedin,
  NULLIF(json_data->>'$.metadata.instagram','')            AS metadata_instagram,
  NULLIF(json_data->>'$.metadata.publicEmail','')          AS metadata_public_email,
  NULLIF(json_data->>'$.metadata.nickname','')             AS metadata_nickname,
  JSON_EXTRACT(json_data, '$.metadata')                    AS metadata_json,
  json_data->>'$.timezone'                                 AS timezone,
  json_data->>'$.userType'                                 AS user_type,
  json_data->>'$.membershipType'                           AS membership_type,
  STR_TO_DATE(json_data->>'$.lastFetchDate', '%Y-%m-%dT%H:%i:%s') AS last_fetch_date,
  STR_TO_DATE(json_data->>'$.lastSeenDate', '%Y-%m-%dT%H:%i:%s')  AS last_seen_date,
  CAST(json_data->>'$.followersCount' AS UNSIGNED)         AS followers_count,
  CAST(json_data->>'$.followingsCount' AS UNSIGNED)        AS followings_count,
  CAST(json_data->>'$.isActive' AS UNSIGNED)               AS is_active,
  CAST(json_data->>'$.hardDeleted' AS UNSIGNED)            AS hard_deleted,
  CAST(json_data->>'$.syncRequired' AS UNSIGNED)           AS sync_required,
  STR_TO_DATE(json_data->>'$.lastSyncDate', '%Y-%m-%dT%H:%i:%s') AS last_sync_date,
  CAST(json_data->>'$.lastSyncBy' AS UNSIGNED)             AS last_sync_by,
  CAST(json_data->>'$.suspended' AS UNSIGNED)              AS is_suspended,
  NULLIF(json_data->>'$.alternateEmail','')                AS alternate_email,
  json_data->>'$.hash'                                     AS hash,
  json_data->>'$.user_email'                               AS user_email,
  json_data->>'$.type'                                     AS entity_type,
  json_data->>'$._entityName'                              AS entity_name
FROM wscpa_breezio.staging_users;
