DROP TABLE IF EXISTS wscpa_dw.dw_breezio_posts;

CREATE TABLE wscpa_dw.dw_breezio_posts
(
    id                      BIGINT UNSIGNED NOT NULL,
    user_id                 BIGINT UNSIGNED NULL,
    root_folder_id          VARCHAR(100) NULL,
    title                   TEXT NULL,
    slug                    VARCHAR(500) NULL,
    subtitle                TEXT NULL,
    post_type               VARCHAR(50) NULL,
    format                  VARCHAR(50) NULL,
    content_json            JSON NULL,
    creation_date           DATETIME NULL,
    modified_date           DATETIME NULL,
    publish_date            DATETIME NULL,
    last_activity_date      DATETIME NULL,
    last_conference_date    DATETIME NULL,
    status                  VARCHAR(50) NULL,
    is_deleted              TINYINT UNSIGNED NULL,
    is_featured             TINYINT UNSIGNED NULL,
    is_org_featured         TINYINT UNSIGNED NULL,
    hide_comments           TINYINT UNSIGNED NULL,
    version                 INT UNSIGNED NULL,
    source_id               VARCHAR(100) NULL,
    score                   INT NULL,
    view_count              INT UNSIGNED NULL,
    is_private              TINYINT UNSIGNED NULL,
    organization_id         BIGINT UNSIGNED NULL,
    notes_count             INT UNSIGNED NULL,
    metadata_json           JSON NULL,
    vote_score              INT NULL,
    poster_id               BIGINT UNSIGNED NULL,
    portal_id               BIGINT UNSIGNED NULL,
    external_id             VARCHAR(255) NULL,
    image_path              TEXT NULL,
    info_json               JSON NULL,
    only_path_accessible    TINYINT UNSIGNED NULL,
    unique_view_count       INT UNSIGNED NULL,
    price                   DECIMAL(18,2) NULL,
    purchase_count          INT UNSIGNED NULL,
    post_hash               VARCHAR(255) NULL,
    comments_mode           VARCHAR(50) NULL,
    entity_type             VARCHAR(50) NULL,
    entity_name             VARCHAR(50) NULL,
    tags_connected_json     JSON NULL,
    user_json               JSON NULL,
    purchased_item          TINYINT UNSIGNED NULL,
    organization_json       JSON NULL,
    display_date            VARCHAR(100) NULL,
    date_type               VARCHAR(100) NULL,

    PRIMARY KEY (id)
)
ENGINE=InnoDB;
