DROP TABLE IF EXISTS wscpa_dw.dw_breezio_users;

CREATE TABLE wscpa_dw.dw_breezio_users
(
    id                          BIGINT UNSIGNED NOT NULL,
    unverified_email            VARCHAR(255) NULL,
    username                    VARCHAR(255) NULL,
    role                        VARCHAR(50) NULL,
    first_name                  VARCHAR(100) NULL,
    last_name                   VARCHAR(100) NULL,
    status                      VARCHAR(50) NULL,
    state                       INT UNSIGNED NULL,
    image_path                  TEXT NULL,
    cv_path                     VARCHAR(500) NULL,
    is_deleted                  TINYINT UNSIGNED NULL,
    is_featured                 TINYINT UNSIGNED NULL,
    birthdate                   DATE NULL,
    creation_date               DATETIME NULL,
    last_modified_by            BIGINT UNSIGNED NULL,
    modified_date               DATETIME NULL,
    bio                         TEXT NULL,
    short_bio                   VARCHAR(255) NULL,
    gender                      VARCHAR(50) NULL,
    website                     VARCHAR(500) NULL,
    office_hours                VARCHAR(255) NULL,
    view_count                  INT UNSIGNED NULL,
    posts_count                 INT UNSIGNED NULL,
    comments_count              INT UNSIGNED NULL,
    votes_count                 INT UNSIGNED NULL,
    score                       INT NULL,
    foo                         INT NULL,
    bar                         INT NULL,
    active_key                  VARCHAR(255) NULL,
    title                       VARCHAR(255) NULL,
    version                     INT UNSIGNED NULL,
    invited_by                  BIGINT UNSIGNED NULL,
    invited_count               INT UNSIGNED NULL,
    portal_id                   BIGINT UNSIGNED NULL,
    original_portal_id          BIGINT UNSIGNED NULL,
    external_id                 BIGINT UNSIGNED NULL,
    external_id2                BIGINT UNSIGNED NULL,
    root_folder_id              VARCHAR(100) NULL,
    is_private                  TINYINT UNSIGNED NULL,
    cloak_mode                  TINYINT UNSIGNED NULL,
    privacy                     VARCHAR(50) NULL,

    metadata_company            VARCHAR(255) NULL,
    metadata_city               VARCHAR(255) NULL,
    metadata_country            VARCHAR(255) NULL,
    metadata_phone              VARCHAR(100) NULL,
    metadata_twitter            VARCHAR(255) NULL,
    metadata_facebook           VARCHAR(255) NULL,
    metadata_linkedin           VARCHAR(500) NULL,
    metadata_instagram          VARCHAR(255) NULL,
    metadata_public_email       VARCHAR(255) NULL,
    metadata_nickname           VARCHAR(255) NULL,
    metadata_json               JSON NULL,

    timezone                    VARCHAR(100) NULL,
    user_type                   VARCHAR(50) NULL,
    membership_type             VARCHAR(100) NULL,
    last_fetch_date             DATETIME NULL,
    last_seen_date              DATETIME NULL,
    followers_count             INT UNSIGNED NULL,
    followings_count            INT UNSIGNED NULL,
    is_active                   TINYINT UNSIGNED NULL,
    hard_deleted                TINYINT UNSIGNED NULL,
    sync_required               TINYINT UNSIGNED NULL,
    last_sync_date              DATETIME NULL,
    last_sync_by                BIGINT UNSIGNED NULL,
    is_suspended                TINYINT UNSIGNED NULL,
    alternate_email             VARCHAR(255) NULL,
    hash                        VARCHAR(64) NULL,
    user_email                  VARCHAR(255) NULL,
    entity_type                 VARCHAR(50) NULL,
    entity_name                 VARCHAR(50) NULL,

    PRIMARY KEY (id)
)
ENGINE=InnoDB;
