CREATE TABLE wscpa_dw.dim_Dates
(
    DatesKey                    INT AUTO_INCREMENT PRIMARY KEY,
    Date                        DATE NOT NULL,
    FullDate                    VARCHAR(10),
    CalendarYear                INT,
    CalendarYearAndQuarter      CHAR(8),
    CalendarQuarter             TINYINT,
    CalendarYearAndMonth        CHAR(8),
    CalendarMonthNumber         TINYINT,
    CalendarMonthName           VARCHAR(10),
    CalendarMonthAbbreviation   CHAR(3),
    WeekOfCalendarYear          TINYINT,
    ISOWeekOfYear               TINYINT,
    WeekOfMonth                 TINYINT,
    DayOfCalendarYear           SMALLINT,
    DayOfMonth                  TINYINT,
    DayOfMonthOrdinal           VARCHAR(5),
    DayOfWeek                   TINYINT,
    DayOfWeekName               VARCHAR(9),
    DayType                     VARCHAR(12),
    HolidayName                 VARCHAR(24),
    DuesYearBeginDate           DATE,
    DuesYearEndDate             DATE,
    DuesYearName                CHAR(4),
    DuesYearAndQuarter          CHAR(8),
    DuesQuarter                 TINYINT,
    DuesYearAndPeriod           CHAR(8),
    DuesPeriod                  TINYINT,
    WeekOfDuesYear              TINYINT,
    DayOfDuesYear               SMALLINT,
    EventYearBeginDate          DATE,
    EventYearEndDate            DATE,
    EventYearName               CHAR(4),
    EventYearAndQuarter         CHAR(8),
    EventQuarter                TINYINT,
    EventYearAndPeriod          CHAR(8),
    EventPeriod                 TINYINT,
    WeekOfEventYear             TINYINT,
    DayOfEventYear              SMALLINT,
    AccountingYearBeginDate     DATE,
    AccountingYearEndDate       DATE,
    AccountingYearName          CHAR(4),
    AccountingYearAndQuarter    CHAR(8),
    AccountingQuarter           TINYINT,
    AccountingYearAndPeriod     CHAR(8),
    AccountingPeriod            TINYINT,
    WeekOfAccountingYear        TINYINT,
    DayOfAccountingYear         SMALLINT,
    PeriodCounter               INT,
    UNIQUE KEY UQ_dim_Dates_Date (Date)
) ENGINE=InnoDB;
